### ISSUE TITLE
ValueError at Size Analysis System at the example from the documentation

### ISSUE THREAD

**Issue by Arne-He** [mass-project/mass_api_client#103]
Version: mass-api-client (0.1.1) (current version from pip)

Traceback (most recent call last):
  File "/home/arne/Schreibtisch/mass_client_test/sys3/size_test.py", line 22, in <module>
    process_analyses(analysis_system_instance, size_analysis, sleep_time=7)
  File "/usr/local/lib/python3.5/dist-packages/mass_api_client/utils.py", line 87, in process_analyses
    analysis_method(analysis_request)
  File "/home/arne/Schreibtisch/mass_client_test/sys3/size_test.py", line 12, in size_analysis
    json_report_objects={'size_report': ('size_report', size_report)},
  File "/usr/local/lib/python3.5/dist-packages/mass_api_client/resources/scheduled_analysis.py", line 37, in create_report
    return Report.create(self, json_report_objects=json_report_objects, raw_report_objects=raw_report_objects, additional_metadata=additional_metadata, tags=tags, analysis_date=analysis_date)
  File "/usr/local/lib/python3.5/dist-packages/mass_api_client/resources/report.py", line 54, in create
    additional_metadata=additional_metadata, force_multipart=True)
  File "/usr/local/lib/python3.5/dist-packages/mass_api_client/resources/base.py", line 94, in _create
    deserialized = cls._deserialize(response_data)
  File "/usr/local/lib/python3.5/dist-packages/mass_api_client/resources/base.py", line 37, in _deserialize
    raise ValueError('An error occurred during object deserialization: {}'.format(errors))
ValueError: An error occurred during object deserialization: {'analysis_date': ['Not a valid datetime.']}

**Comment by Arne-He** [comment]
It seems to be fixed after updating server and api client to version 0.2 .
